import {
  ABSOLUTE_MAXIMUM_COMMON,
  DERATING_CURVES,
  LUMINOUS_FLUX_BINS_LM,
  VOLTAGE_BINS,
} from "@/domain/led/ledCurves";
import {
  LM301H_EVO_CHROMATICITY_QUADS,
  LM301H_MACADAM_ELLIPSES,
} from "@/domain/led/ledChromaticity";
import type { LedDefinition, LedReference } from "@/domain/contracts";

function lmBinRecord(
  codes: string[],
): NonNullable<LedDefinition["luminousFluxBinsLm"]> {
  const result: NonNullable<LedDefinition["luminousFluxBinsLm"]> = {};
  for (const code of codes) result[code] = LUMINOUS_FLUX_BINS_LM[code];
  return result;
}

function ppfBin(minPpfUmolS: number, maxPpfUmolS: number) {
  return {
    minPpfUmolS,
    maxPpfUmolS,
    typicalPpfUmolS: (minPpfUmolS + maxPpfUmolS) / 2,
  };
}

const COMMON_REFERENCE = {
  currentMA: 65,
  solderPointTempC: 25,
  forwardVoltageV: 2.7,
};
const COMMON_STANDARD = {
  manufacturer: "Samsung",
  family: "LM301H",
  package: "3030",
  packageSizeMm: [3, 3, 0.7],
  curveSetId: "lm301hStandard",
  absoluteMaximum: ABSOLUTE_MAXIMUM_COMMON,
  thermalResistanceJunctionToSolderPointCW: 7.5,
  beamAngleDeg: 120,
  voltageBins: VOLTAGE_BINS,
  deratingCurves: DERATING_CURVES.lm301hStandard,
  systemEfficiency: 1.0,
};
const COMMON_EVO = {
  manufacturer: "Samsung",
  family: "LM301H EVO",
  package: "3030",
  packageSizeMm: [3, 3, 0.8],
  curveSetId: "lm301hEvo",
  absoluteMaximum: ABSOLUTE_MAXIMUM_COMMON,
  thermalResistanceJunctionToSolderPointCW: 7.5,
  beamAngleDeg: 120,
  voltageBins: VOLTAGE_BINS,
  deratingCurves: DERATING_CURVES.lm301hEvo,
  systemEfficiency: 1.0,
};

function noPpfReference(note: string): LedReference {
  return { ...COMMON_REFERENCE, source: "notProvided", note };
}

function datasheetPpfPpe(ppfUmolS: number, ppeUmolJ: number): LedReference {
  return {
    ...COMMON_REFERENCE,
    ppfUmolS,
    ppeUmolJ,
    source: "datasheet",
    note: "Datasheet PPF/PPE table; Samsung marks PPF/PPE as calculated, reference only.",
  };
}

function evoBinReference(
  minPpfUmolS: number,
  maxPpfUmolS: number,
): LedReference {
  const bin = ppfBin(minPpfUmolS, maxPpfUmolS);
  return {
    ...COMMON_REFERENCE,
    ppfUmolS: bin.typicalPpfUmolS,
    ppfRangeUmolS: bin,
    ppeUmolJ: bin.typicalPpfUmolS / (0.065 * 2.7),
    source: "datasheetBinMidpoint",
    note: "Datasheet gives PPF min/max bins, not a single typical. ppfUmolS is the bin midpoint.",
  };
}

const HOMEPAGE_LM301H_5000K_CRI80 = {
  currentMA: 65,
  solderPointTempC: 25,
  cctK: 5000,
  cri: 80,
  forwardVoltageV: 2.7,
  nominalWattageW: 0.2,
  ppfUmolS: 0.56,
  ppeUmolJ: 3.1,
  note: "User-provided Samsung homepage tech spec. Wattage appears nominal/rounded; compute electrical power from V * A for calculations.",
};
const HOMEPAGE_LM301H_EVO_5000K_CRI80 = {
  currentMA: 65,
  solderPointTempC: 25,
  cctK: 5000,
  cri: 80,
  forwardVoltageV: 2.7,
  nominalWattageW: 0.2,
  ppfUmolS: 0.56,
  ppeUmolJ: 3.14,
  note: "User-provided Samsung homepage tech spec. Wattage appears nominal/rounded; compute electrical power from V * A for calculations.",
};
const LED_LIBRARY_V2_DATA = {
  lm301h_cri70_3000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri70_3000k",
    name: "Samsung LM301H 3000K CRI70",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI70).",
    },
    criMin: 70,
    cctK: 3000,
    colorCode: "V",
    productCodeTemplate: "SPMWHD32AMH3XAV{0|5}S0",
    luminousFluxBinCodes: ["SJ", "SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SJ", "SK", "SL"]),
    chromaticityRank: "V0/V5",
    chromaticityBins: ["VE", "VF", "VG", "VH", "VJ", "VK", "VL", "VM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.V5,
    reference: noPpfReference(
      "CRI70 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI70_Rev.2.2.pdf"],
  },
  lm301h_cri70_3500k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri70_3500k",
    name: "Samsung LM301H 3500K CRI70",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI70).",
    },
    criMin: 70,
    cctK: 3500,
    colorCode: "U",
    productCodeTemplate: "SPMWHD32AMH3XAU{0|5}S0",
    luminousFluxBinCodes: ["SJ", "SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SJ", "SK", "SL"]),
    chromaticityRank: "U0/U5",
    chromaticityBins: ["UE", "UF", "UG", "UH", "UJ", "UK", "UL", "UM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.U5,
    reference: noPpfReference(
      "CRI70 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI70_Rev.2.2.pdf"],
  },
  lm301h_cri70_4000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri70_4000k",
    name: "Samsung LM301H 4000K CRI70",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 42,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI70).",
    },
    criMin: 70,
    cctK: 4000,
    colorCode: "T",
    productCodeTemplate: "SPMWHD32AMH3XAT{0|5}S0",
    luminousFluxBinCodes: ["SK", "SL", "SM"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL", "SM"]),
    chromaticityRank: "T0/T5",
    chromaticityBins: ["TE", "TF", "TG", "TH", "TJ", "TK", "TL", "TM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.T5,
    reference: noPpfReference(
      "CRI70 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI70_Rev.2.2.pdf"],
  },
  lm301h_cri70_5000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri70_5000k",
    name: "Samsung LM301H 5000K CRI70",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 42,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI70).",
    },
    criMin: 70,
    cctK: 5000,
    colorCode: "R",
    productCodeTemplate: "SPMWHD32AMH3XAR{0|5}S0",
    luminousFluxBinCodes: ["SK", "SL", "SM"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL", "SM"]),
    chromaticityRank: "R0/R5",
    chromaticityBins: ["RE", "RF", "RG", "RH", "RJ", "RK", "RL", "RM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.R5,
    reference: noPpfReference(
      "CRI70 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI70_Rev.2.2.pdf"],
  },
  lm301h_cri70_5700k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri70_5700k",
    name: "Samsung LM301H 5700K CRI70",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 42,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI70).",
    },
    criMin: 70,
    cctK: 5700,
    colorCode: "Q",
    productCodeTemplate: "SPMWHD32AMH3XAQ{0|5}S0",
    luminousFluxBinCodes: ["SK", "SL", "SM"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL", "SM"]),
    chromaticityRank: "Q0/Q5",
    chromaticityBins: ["QE", "QF", "QG", "QH", "QJ", "QK", "QL", "QM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.Q5,
    reference: noPpfReference(
      "CRI70 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI70_Rev.2.2.pdf"],
  },
  lm301h_cri80_2200k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_2200k",
    name: "Samsung LM301H 2200K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 34,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 2200,
    colorCode: "Y",
    productCodeTemplate: "SPMWHD32AMH5XAY{0|5}S{0|G}",
    luminousFluxBinCodes: ["SF", "SG", "SH"],
    luminousFluxBinsLm: lmBinRecord(["SF", "SG", "SH"]),
    chromaticityRank: "Y0/Y5",
    chromaticityBins: ["YE", "YF", "YG", "YH", "YJ", "YK", "YL", "YM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.Y5,
    reference: noPpfReference(
      "CRI80 datasheet PPF/PPE table starts at 2700K; 2200K has luminous-flux bins but no PPF/PPE value.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_2700k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_2700k",
    name: "Samsung LM301H 2700K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 38,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 2700,
    colorCode: "W",
    productCodeTemplate: "SPMWHD32AMH5XAW{0|5}S{0|J}",
    luminousFluxBinCodes: ["SH", "SJ", "SK"],
    luminousFluxBinsLm: lmBinRecord(["SH", "SJ", "SK"]),
    chromaticityRank: "W0/W5",
    chromaticityBins: ["WE", "WF", "WG", "WH", "WJ", "WK", "WL", "WM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.W5,
    reference: datasheetPpfPpe(0.5, 2.83),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_3000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_3000k",
    name: "Samsung LM301H 3000K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 3000,
    colorCode: "V",
    productCodeTemplate: "SPMWHD32AMH5XAV{0|5}S{0|K}",
    luminousFluxBinCodes: ["SJ", "SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SJ", "SK", "SL"]),
    chromaticityRank: "V0/V5",
    chromaticityBins: ["VE", "VF", "VG", "VH", "VJ", "VK", "VL", "VM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.V5,
    reference: datasheetPpfPpe(0.511, 2.89),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_3500k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_3500k",
    name: "Samsung LM301H 3500K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 3500,
    colorCode: "U",
    productCodeTemplate: "SPMWHD32AMH5XAU{0|5}S{0|L}",
    luminousFluxBinCodes: ["SJ", "SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SJ", "SK", "SL"]),
    chromaticityRank: "U0/U5",
    chromaticityBins: ["UE", "UF", "UG", "UH", "UJ", "UK", "UL", "UM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.U5,
    reference: datasheetPpfPpe(0.517, 2.92),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_4000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_4000k",
    name: "Samsung LM301H 4000K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 4000,
    colorCode: "T",
    productCodeTemplate: "SPMWHD32AMH5XAT{0|5}S{0|L}",
    luminousFluxBinCodes: ["SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL"]),
    chromaticityRank: "T0/T5",
    chromaticityBins: ["TE", "TF", "TG", "TH", "TJ", "TK", "TL", "TM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.T5,
    reference: datasheetPpfPpe(0.528, 2.98),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_5000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_5000k",
    name: "Samsung LM301H 5000K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 42,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 5000,
    colorCode: "R",
    productCodeTemplate: "SPMWHD32AMH5XAR{0|5}S{0|L|2}",
    luminousFluxBinCodes: ["SK", "SL", "SM"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL", "SM"]),
    chromaticityRank: "R0/R5",
    chromaticityBins: ["RE", "RF", "RG", "RH", "RJ", "RK", "RL", "RM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.R5,
    reference: datasheetPpfPpe(0.544, 3.08),
    manufacturerHomepageTypical: HOMEPAGE_LM301H_5000K_CRI80,
    sourceDocuments: [
      "Data_Sheet_LM301H_CRI80_Rev.5.4.pdf",
      "Samsung homepage tech spec supplied by user",
    ],
  },
  lm301h_cri80_5700k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_5700k",
    name: "Samsung LM301H 5700K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 5700,
    colorCode: "Q",
    productCodeTemplate: "SPMWHD32AMH5XAQ{0|5}S{0|L}",
    luminousFluxBinCodes: ["SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL"]),
    chromaticityRank: "Q0/Q5",
    chromaticityBins: ["QE", "QF", "QG", "QH", "QJ", "QK", "QL", "QM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.Q5,
    reference: datasheetPpfPpe(0.542, 3.07),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri80_6500k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri80_6500k",
    name: "Samsung LM301H 6500K CRI80",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 40,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI80).",
    },
    criMin: 80,
    cctK: 6500,
    colorCode: "P",
    productCodeTemplate: "SPMWHD32AMH5XAP{0|5}S{0|L}",
    luminousFluxBinCodes: ["SK", "SL"],
    luminousFluxBinsLm: lmBinRecord(["SK", "SL"]),
    chromaticityRank: "P0/P5",
    chromaticityBins: ["PE", "PF", "PG", "PH", "PJ", "PK", "PL", "PM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.P5,
    reference: datasheetPpfPpe(0.541, 3.06),
    sourceDocuments: ["Data_Sheet_LM301H_CRI80_Rev.5.4.pdf"],
  },
  lm301h_cri90_2700k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_2700k",
    name: "Samsung LM301H 2700K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 32,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 2700,
    colorCode: "W",
    productCodeTemplate: "SPMWHD32AMH7XAW{0|5}S0",
    luminousFluxBinCodes: ["SF", "SG"],
    luminousFluxBinsLm: lmBinRecord(["SF", "SG"]),
    chromaticityRank: "W0/W5",
    chromaticityBins: ["WE", "WF", "WG", "WH", "WJ", "WK", "WL", "WM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.W5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_3000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_3000k",
    name: "Samsung LM301H 3000K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 32,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 3000,
    colorCode: "V",
    productCodeTemplate: "SPMWHD32AMH7XAV{0|5}S0",
    luminousFluxBinCodes: ["SF", "SG"],
    luminousFluxBinsLm: lmBinRecord(["SF", "SG"]),
    chromaticityRank: "V0/V5",
    chromaticityBins: ["VE", "VF", "VG", "VH", "VJ", "VK", "VL", "VM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.V5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_3500k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_3500k",
    name: "Samsung LM301H 3500K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 34,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 3500,
    colorCode: "U",
    productCodeTemplate: "SPMWHD32AMH7XAU{0|5}S0",
    luminousFluxBinCodes: ["SG", "SH"],
    luminousFluxBinsLm: lmBinRecord(["SG", "SH"]),
    chromaticityRank: "U0/U5",
    chromaticityBins: ["UE", "UF", "UG", "UH", "UJ", "UK", "UL", "UM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.U5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_4000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_4000k",
    name: "Samsung LM301H 4000K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 34,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 4000,
    colorCode: "T",
    productCodeTemplate: "SPMWHD32AMH7XAT{0|5}S0",
    luminousFluxBinCodes: ["SG", "SH"],
    luminousFluxBinsLm: lmBinRecord(["SG", "SH"]),
    chromaticityRank: "T0/T5",
    chromaticityBins: ["TE", "TF", "TG", "TH", "TJ", "TK", "TL", "TM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.T5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_5000k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_5000k",
    name: "Samsung LM301H 5000K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 36,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 5000,
    colorCode: "R",
    productCodeTemplate: "SPMWHD32AMH7XAR{0|5}S0",
    luminousFluxBinCodes: ["SG", "SH", "SJ"],
    luminousFluxBinsLm: lmBinRecord(["SG", "SH", "SJ"]),
    chromaticityRank: "R0/R5",
    chromaticityBins: ["RE", "RF", "RG", "RH", "RJ", "RK", "RL", "RM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.R5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_5700k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_5700k",
    name: "Samsung LM301H 5700K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 36,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 5700,
    colorCode: "Q",
    productCodeTemplate: "SPMWHD32AMH7XAQ{0|5}S0",
    luminousFluxBinCodes: ["SG", "SH", "SJ"],
    luminousFluxBinsLm: lmBinRecord(["SG", "SH", "SJ"]),
    chromaticityRank: "Q0/Q5",
    chromaticityBins: ["QE", "QF", "QG", "QH", "QJ", "QK", "QL", "QM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.Q5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_cri90_6500k: {
    ...COMMON_STANDARD,
    id: "lm301h_cri90_6500k",
    name: "Samsung LM301H 6500K CRI90",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      luminousFluxLm: 36,
      source:
        "User-provided (datasheet typical test condition for spectrum, CRI90).",
    },
    criMin: 90,
    cctK: 6500,
    colorCode: "P",
    productCodeTemplate: "SPMWHD32AMH7XAP{0|5}S0",
    luminousFluxBinCodes: ["SG", "SH", "SJ"],
    luminousFluxBinsLm: lmBinRecord(["SG", "SH", "SJ"]),
    chromaticityRank: "P0/P5",
    chromaticityBins: ["PE", "PF", "PG", "PH", "PJ", "PK", "PL", "PM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.P5,
    reference: noPpfReference(
      "CRI90 datasheet provides luminous-flux bins and spectra, but no PPF/PPE table.",
    ),
    sourceDocuments: ["Data_Sheet_LM301H_CRI90_Rev.2.2.pdf"],
  },
  lm301h_evo_3000k: {
    ...COMMON_EVO,
    id: "lm301h_evo_3000k",
    name: "Samsung LM301H EVO 3000K",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.557,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO).",
    },
    cctK: 3000,
    colorCode: "V0",
    productCodeTemplate: "SPMWHD32AMH0XAV0PV",
    ppfBin: ppfBin(0.494, 0.557),
    chromaticityRank: "V0",
    chromaticityBins: ["VE", "VF", "VG", "VH", "VJ", "VK", "VL", "VM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.V5,
    chromaticityQuads: {
      VW: LM301H_EVO_CHROMATICITY_QUADS.VW,
      VX: LM301H_EVO_CHROMATICITY_QUADS.VX,
      VY: LM301H_EVO_CHROMATICITY_QUADS.VY,
      VZ: LM301H_EVO_CHROMATICITY_QUADS.VZ,
    },
    reference: evoBinReference(0.494, 0.557),
    sourceDocuments: ["Data_Sheet_LM301H_EVO_Rev.2.1.pdf"],
  },
  lm301h_evo_4000k: {
    ...COMMON_EVO,
    id: "lm301h_evo_4000k",
    name: "Samsung LM301H EVO 4000K",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.572,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO).",
    },
    cctK: 4000,
    colorCode: "T0",
    productCodeTemplate: "SPMWHD32AMH0XAT0PT",
    ppfBin: ppfBin(0.507, 0.572),
    chromaticityRank: "T0",
    chromaticityBins: ["TE", "TF", "TG", "TH", "TJ", "TK", "TL", "TM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.T5,
    chromaticityQuads: {
      TW: LM301H_EVO_CHROMATICITY_QUADS.TW,
      TX: LM301H_EVO_CHROMATICITY_QUADS.TX,
      TY: LM301H_EVO_CHROMATICITY_QUADS.TY,
      TZ: LM301H_EVO_CHROMATICITY_QUADS.TZ,
    },
    reference: evoBinReference(0.507, 0.572),
    sourceDocuments: ["Data_Sheet_LM301H_EVO_Rev.2.1.pdf"],
  },
  lm301h_evo_5000k: {
    ...COMMON_EVO,
    id: "lm301h_evo_5000k",
    name: "Samsung LM301H EVO 5000K",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.587,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO).",
    },
    cctK: 5000,
    colorCode: "R0",
    productCodeTemplate: "SPMWHD32AMH0XAR0PR",
    ppfBin: ppfBin(0.52, 0.587),
    chromaticityRank: "R0",
    chromaticityBins: ["RE", "RF", "RG", "RH", "RJ", "RK", "RL", "RM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.R5,
    chromaticityQuads: {
      RW: LM301H_EVO_CHROMATICITY_QUADS.RW,
      RX: LM301H_EVO_CHROMATICITY_QUADS.RX,
      RY: LM301H_EVO_CHROMATICITY_QUADS.RY,
      RZ: LM301H_EVO_CHROMATICITY_QUADS.RZ,
    },
    reference: evoBinReference(0.52, 0.587),
    manufacturerHomepageTypical: HOMEPAGE_LM301H_EVO_5000K_CRI80,
    sourceDocuments: [
      "Data_Sheet_LM301H_EVO_Rev.2.1.pdf",
      "Samsung homepage tech spec supplied by user",
    ],
  },
  lm301h_evo_6500k: {
    ...COMMON_EVO,
    id: "lm301h_evo_6500k",
    name: "Samsung LM301H EVO 6500K",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.587,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO).",
    },
    cctK: 6500,
    colorCode: "P0",
    productCodeTemplate: "SPMWHD32AMH0XAP0PP",
    ppfBin: ppfBin(0.52, 0.587),
    chromaticityRank: "P0",
    chromaticityBins: ["PE", "PF", "PG", "PH", "PJ", "PK", "PL", "PM"],
    macAdamEllipse: LM301H_MACADAM_ELLIPSES.P5,
    chromaticityQuads: {
      PW: LM301H_EVO_CHROMATICITY_QUADS.PW,
      PX: LM301H_EVO_CHROMATICITY_QUADS.PX,
      PY: LM301H_EVO_CHROMATICITY_QUADS.PY,
      PZ: LM301H_EVO_CHROMATICITY_QUADS.PZ,
    },
    reference: evoBinReference(0.52, 0.587),
    sourceDocuments: ["Data_Sheet_LM301H_EVO_Rev.2.1.pdf"],
  },
  lm301h_evo_mint_ma: {
    ...COMMON_EVO,
    id: "lm301h_evo_mint_ma",
    name: "Samsung LM301H EVO Mint White MA",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.595,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO mint white).",
      note: "Mint white is treated as equivalent across MA/MB for spectrum anchoring unless a per-bin value is available.",
    },
    colorName: "Mint White MA",
    colorCode: "MA",
    productCodeTemplate: "SPMWHD32AMH0XAMAPL",
    ppfBin: ppfBin(0.52, 0.587),
    chromaticityRank: "MA",
    chromaticityBins: ["M1", "M2"],
    chromaticityQuads: {
      M1: LM301H_EVO_CHROMATICITY_QUADS.M1,
      M2: LM301H_EVO_CHROMATICITY_QUADS.M2,
    },
    reference: evoBinReference(0.52, 0.587),
    sourceDocuments: ["Data_Sheet_LM301H_EVO_Rev.2.1.pdf"],
  },
  lm301h_evo_mint_mb: {
    ...COMMON_EVO,
    id: "lm301h_evo_mint_mb",
    name: "Samsung LM301H EVO Mint White MB",
    beamAngleDeg: 90,
    spectrumCalibration: {
      currentMA: 65,
      solderPointTempC: 25,
      ppfUmolS: 0.595,
      source:
        "User-provided (datasheet typical test condition for spectrum, LM301H EVO mint white).",
      note: "Mint white is treated as equivalent across MA/MB for spectrum anchoring unless a per-bin value is available.",
    },
    colorName: "Mint White MB",
    colorCode: "MB",
    productCodeTemplate: "SPMWHD32AMH0XAMBPM",
    ppfBin: ppfBin(0.528, 0.595),
    chromaticityRank: "MB",
    chromaticityBins: ["M3", "M4"],
    chromaticityQuads: {
      M3: LM301H_EVO_CHROMATICITY_QUADS.M3,
      M4: LM301H_EVO_CHROMATICITY_QUADS.M4,
    },
    reference: evoBinReference(0.528, 0.595),
    sourceDocuments: ["Data_Sheet_LM301H_EVO_Rev.2.1.pdf"],
  },
} satisfies Record<string, LedDefinition>;

export const LED_LIBRARY_V2: Record<string, LedDefinition> =
  LED_LIBRARY_V2_DATA;
